/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "update_event_message.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(I2CWriteEvent, I2CWriteEvent, AUTO)

PB_BIND(SPIWriteEvent, SPIWriteEvent, AUTO)
